// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1_QksRsTPExPnYH9RjyHx57WuNXUwpM',
    appId: '1:911882774133:web:969a448fd2265b3823fa3c',
    messagingSenderId: '911882774133',
    projectId: 'jonghong-72a28',
    authDomain: 'jonghong-72a28.firebaseapp.com',
    storageBucket: 'jonghong-72a28.appspot.com',
    measurementId: 'G-S6HRYCG5X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2swrtXhKURreuTAWilLwJiklHDo4Ea4',
    appId: '1:911882774133:android:73ef0c7e20ff0c9a23fa3c',
    messagingSenderId: '911882774133',
    projectId: 'jonghong-72a28',
    storageBucket: 'jonghong-72a28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvUH3O50D60syqQkpF3uUpmJzGACK6LU',
    appId: '1:911882774133:ios:5350fd6037118c1323fa3c',
    messagingSenderId: '911882774133',
    projectId: 'jonghong-72a28',
    storageBucket: 'jonghong-72a28.appspot.com',
    iosClientId: '911882774133-tts1d8dronr6t5u3qq4sdgc8783s7dda.apps.googleusercontent.com',
    iosBundleId: 'com.example.jonghong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEvUH3O50D60syqQkpF3uUpmJzGACK6LU',
    appId: '1:911882774133:ios:4e9104f72689181723fa3c',
    messagingSenderId: '911882774133',
    projectId: 'jonghong-72a28',
    storageBucket: 'jonghong-72a28.appspot.com',
    iosClientId: '911882774133-n61nd9k7q5tt1u6p6ag9oa3tne7nitfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.jonghong.RunnerTests',
  );
}
