// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXwO0JUoDbmGpLTIabNh0ogvIVvUoXkI',
    appId: '1:551608440416:web:143a4e9afbb331d3769505',
    messagingSenderId: '551608440416',
    projectId: 'jonghong-4c2ab',
    authDomain: 'jonghong-4c2ab.firebaseapp.com',
    storageBucket: 'jonghong-4c2ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3xcM7alQ_4rei5-JFwy8jdcl-Wqw4VQ',
    appId: '1:551608440416:android:46170ec626ab2689769505',
    messagingSenderId: '551608440416',
    projectId: 'jonghong-4c2ab',
    storageBucket: 'jonghong-4c2ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVDgmdhGiIYdc8Tk8P_kqpfPGiTD9ybo',
    appId: '1:551608440416:ios:250f6876a2fe4e7f769505',
    messagingSenderId: '551608440416',
    projectId: 'jonghong-4c2ab',
    storageBucket: 'jonghong-4c2ab.appspot.com',
    iosBundleId: 'com.example.jonghong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxVDgmdhGiIYdc8Tk8P_kqpfPGiTD9ybo',
    appId: '1:551608440416:ios:250f6876a2fe4e7f769505',
    messagingSenderId: '551608440416',
    projectId: 'jonghong-4c2ab',
    storageBucket: 'jonghong-4c2ab.appspot.com',
    iosBundleId: 'com.example.jonghong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTXwO0JUoDbmGpLTIabNh0ogvIVvUoXkI',
    appId: '1:551608440416:web:86dc6e068f80dd17769505',
    messagingSenderId: '551608440416',
    projectId: 'jonghong-4c2ab',
    authDomain: 'jonghong-4c2ab.firebaseapp.com',
    storageBucket: 'jonghong-4c2ab.appspot.com',
  );
}
